function [ transform,  num_iter] = runMatlabICP(local_cloud, global_cloud,...
    Metric, Extrapolate, MaxIterations, InlierRatio, Tolerance)

[transform, num_iter] = pcregrigid_v3(local_cloud,global_cloud, ...
    'Metric', Metric,...
    'Extrapolate',Extrapolate,...
    'MaxIterations',MaxIterations,...
    'InlierRatio',InlierRatio,... % value not actually used as inlier ratio - it is used as maxInlierDistance!
    'Tolerance',Tolerance);

transform = transpose(transform.T);
end

